colorscheme gotham

source ~/.config/kak/plugins/prelude.kak/rc/prelude.kak
source ~/.config/kak/plugins/auto-pairs.kak/rc/auto-pairs.kak
source ~/.config/kak/plugins/distraction-free.kak/rc/distraction-free.kak
source ~/.config/kak/plugins/kakoune-livedown/livedown.kak
source ~/.config/kak/plugins/surround.kak/rc/surround.kak

set-option global tabstop 2
set-option global indentwidth 2
set-option global scrolloff 5,1
set-option global grepcmd 'rg --column'
set-option global completers filename word=all
set-option global autoinfo normal|command|onkey

hook global WinCreate .* %{
  add-highlighter window/ show-whitespaces
  add-highlighter window/ number-lines -relative -hlcursor
  add-highlighter window/ show-matching
}
set-option -add global ui_options ncurses_assistant=none ncurses_change_colors=true ncurses_status_on_top=true

map global normal . ':'                                       -docstring 'enter command prompt'
map global normal ' '.'                                       -docstring 'repeat last insert'
map global normal '#' ': comment-line<ret>'                   -docstring 'comment-line'

# Quoting
map global normal q ': enter-user-mode surround<ret>'
map global normal Q ': surround-enter-insert-mode<ret>'

# Move macros to ^
map global normal ^ q
map global normal <c-6> Q

hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
      map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
      unmap window insert <s-tab> <c-p>
}

hook global WinSetOption filetype=markdown %{
  add-highlighter global/window wrap -word -width 80
}



