colorscheme gotham

set-option global tabstop 2
set-option global indentwidth 2
set-option global completers filename word=all
set-option global autoinfo normal|command|onkey
set-option -add global matching_pairs { } [ ] ( ) \" \" \' \' * * ~ ~ = =
set-option -add global ui_options ncurses_assistant=none ncurses_change_colors=true ncurses_status_on_top=true

map global normal . ':'										-docstring 'enter command prompt'
map global normal <space> ,								-docstring 'leader'
map global normal : '.'										-docstring 'repeat last insert'
map global normal '=' ': format<ret>'			-docstring 'format'

map global goto m '<esc>m;'								-docstring 'matching next char'
map global goto n '<esc>]p;'							-docstring 'next paragraph'
map global goto p '<esc>[p;'							-docstring 'previous paragraph'

hook global InsertCompletionShow .* %{
    map window insert <tab> <C-n>
    map window insert <s-tab> <C-p>
}
